# Generated by Django 3.0.2 on 2020-01-26 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
