# Generated by Django 3.0.2 on 2020-01-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20200126_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='web_lecture_support',
            field=models.BooleanField(default=False),
        ),
    ]
