# Generated by Django 3.0.2 on 2020-01-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seating_capacity', models.IntegerField()),
                ('web_lecture_support', models.BooleanField()),
                ('shape', models.CharField(choices=[('O', 'Oval'), ('R', 'Rectangle'), ('C', 'Canopy'), ('E', 'Elevated')], max_length=1)),
            ],
        ),
    ]
