# Generated by Django 3.0.2 on 2020-01-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200126_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
