# Generated by Django 3.0.2 on 2020-01-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
    ]
