# Generated by Django 3.0.2 on 2020-01-26 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='chapters',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='duration_per_class',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='total_duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(30)]),
        ),
    ]
