# Generated by Django 3.0.2 on 2020-01-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_subject_name'),
        ('student', '0003_relative_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='subject.Subject'),
        ),
    ]
